### ISSUE TITLE
Cursor keys on a real DEC VT320 do not work

### ISSUE THREAD

**Issue by sblendorio** [taviso/123elf#23]
This is a video describing the issue:

https://photos.app.goo.gl/xrRVaprVntwpuuoHA

I configured it in VT100 emulation

**Comment by taviso** [comment]
wow! It's fun to see, even if it doesn't work properly yet :)

I'm surprised vt100 doesn't work, maybe it's because I added `xterm` as the default in `l123set.cf`. If you remove that line (the whole 1010 line) it should use `$TERM` - can you see if it works?

(Note that it only supports a few `$TERM` settings, don't put anything unusual in there)

**Comment by sblendorio** [comment]
Should I recompile after changing l123set.cf? 
![image](https://user-images.githubusercontent.com/2118813/170071351-da231b45-f013-4bcb-afbf-b742efb89433.png)

**Comment by taviso** [comment]
Hmm okay, thanks - I'll trace through what it's doing.

I can see that when you press down it sees `[B` , and I can see in the vt100 definition it has that it thinks `\e[B` is down, so it really should work...weird!

**Comment by sblendorio** [comment]
It's very cool having Lotus 1-2-3 on a real DEC terminal!

**Comment by sblendorio** [comment]
WAIT.... it seems to be working!

**Comment by sblendorio** [comment]
Now it works! Look here, don't know what's changed

https://photos.app.goo.gl/5StsU2oMGmxgYNrt7

I made a git pull and make
