### ISSUE TITLE
Rewrite command line parser for Linux adaptation

### ISSUE THREAD

**Issue by jserv** [taviso/123elf#33]
The original command line parser of Lotus 1-2-3 for UNIX supported deprecated and useless features, and there are some outdated options as following:
* `-f dos` : select a file-name mode to DOS
* `-c` : select lower/upper-case dos file-name mode
* `-n`: run without using a video display

Meanwhile, we might extend the command line parser to support new options such as `--no-banner` / `--show-banner` (#28), `--ignore-case` (file-name mode ignoring the case of the characters), and `--enable-autoexec` / `--disable-autoexec` (#27).

**Comment by taviso** [comment]
I think this is done now. Originally @jserv wrote a patch that recreated argv, but I removed it because I thought It would be cleaner to reuse the same argv array.

It turned out that was the wrong idea, and the original approach was better. That's implemented now, and I think it gives us some flexibility on adding more parameters in future.
